### ISSUE TITLE
R-Insight: Save All Data Objects in a Workspace to a Single File

### ISSUE THREAD

**Issue by brichard1638** [nanxstats/r-base-shortcuts#6]
When working in the R environment, data is created, collected, and used in the form of various list objects, vectors, models, and datasets. By applying the **save.image** function found in Base R, the entire active workspace can be saved to a single data file. The R file extension used must be .RData. In RStudio, data objects are extracted and subsequently converted into an .RData file from the Environment tab.

`save.image(file = "my_work_space.RData")`

To load the entire workspace back into an RStudio active session, apply the following code:
`load("my_work_space.RData")`

NOTE: If no formal file path is provided in the file argument, the file will be saved in the user's Documents folder.

**Comment by nanxstats** [comment]
From the software engineering best practice perspective, I think it's generally recommended to use functions like `save()`, `saveRDS()` for saving (serializing) individual objects, or explicitly save the data needed in a suitable file format, instead of using `save.image()` to save everything. Specific reasons might include:

- **Reproducibility**: Saving the entire global environment reduces reproducibility, as the saved environment may contain state changes not directly tied to the code.
- **Debugging difficulty**: Errors and issues can be much harder to trace and debug, as they could be related to an object saved in the image, not visible in the current script.
- **Security**: Saving the entire global environment can store sensitive information inadvertently if it's present in the environment.
- **Overhead**: Saving an entire environment including all objects can potentially lead to unnecessarily large file sizes.
